REM compile-win.bat
REM This script compiles all .tex files except those listed in "skipFiles" in the current directory
REM The code is automatically generated by ChatGPT 3.5.

@echo off

REM List of filenames to skip
set "skipFiles=newcommands.tex"

for %%f in (*.tex) do (
    REM Check if the current file should be skipped
    echo %skipFiles% | findstr /i /c:"%%~nxf" > nul
    if errorlevel 1 (
        echo Compiling "%%f"
        pdflatex "%%f"
        echo Compiling "%%f" DONE
        echo ==================
    ) else (
        echo Skipping "%%f"
    )
)

echo Compilation finished.
pause